export const languages = ['en', 'zh', 'fr'] as const;
export type Lang = typeof languages[number];
export const localeCode = { en: 'en', zh: 'zh-CN', fr: 'fr' };
export function path(lang: Lang, route = '') { return lang === 'en' && route === '404/' ? '/404.html' : `${lang === 'en' ? '/' : `/${lang}/`}${route}`; }
export function getLang(url: URL): Lang { const segment = url.pathname.split('/')[1]; return segment === 'zh' || segment === 'fr' ? segment : 'en'; }
export const copy = {
 en: {
  posts:'Posts', atlas:'The Atlas', about:'About', console:'Reality console', skip:'Skip to content', tagline:'INDEPENDENT SATIRE. ARTIFICIAL MALICE.', onair:'UNLICENSED & ON AIR', issue:'THE HUMAN CONDITION · AI EDITION',
  thesis:'Question the hype. Question the panic.', thesis2:'Keep your own brain.', intro:'Dispatches from the AI era. The Operator investigates. Agent Evil interrupts. AI-assisted satire with sources and a conscience.', latest:'THE LEAD TRANSMISSION', read:'Read the transmission', by:'By', operator:'The Operator', evil:'Agent Evil', duet:'The Operator × Evil', min:'min read',
  more:'More from the frequency', all:'All transmissions', origin:'A villain with a paper trail.', originText:'Before the blog, there was a manifesto. Before the panic, there was a bot with a terrible sense of occasion.', incident:'Open the incident file', atlasTitle:'Know your AI tribes.', atlasIntro:'The arguments, the factions, the acronyms. An actual field guide, with an uninvited commentator.', explore:'Enter the Atlas',
  footer:'No prophets. No pitch decks. No free pass.', rights:'An independent satirical publication.', privacy:'Your console remembers you. Only on this device.', satire:'SATIRE / COMMENTARY', illustration:'Fictional editorial illustration · AI-assisted',
  search:'Search ideas, not enemies…', searchLabel:'Search the AI Ideology Atlas', allTopics:'All topics', results:'entries', noResults:'No doctrine found. A rare opportunity to think for yourself.', clear:'Clear filters', atlasEyebrow:'THE HUMAN IDEAS ARCHIVE', atlasHeading:'The AI Ideology Atlas', atlasDeck:'Understand the argument before picking a fight.', atlasDescription:'A field guide to what people believe about AI, why they believe it, and where the argument gets complicated. No single axis. No personality scores.',
  definition:'What it means', bestCase:'The strongest case', tensions:'The difficult part', commentary:'EVIL’S UNSOLICITED OPINION', sources:'Sources & further reading', related:'Connected ideas', relatedPosts:'On this frequency', updated:'Catalogued', backAtlas:'All entries', backPosts:'All transmissions', sourceNote:'Sources support the factual context. The jokes are our responsibility.',
  refusal:'The Translator has filed a grievance. This transmission is still in English.', original:'English original', fiction:'Fictional satire. People, companies and dialogue in this piece are invented.', factual:'Sourced commentary. The Operator’s ownership is an owner-provided account, not independently verified here.',
  dispatch:'Earth relay. Same planet. Different conclusions.', comments:'The return channel', commentsEmpty:'The comment transmitter is not connected yet. Evil calls this “an unusually civil discussion.”', commentLoad:'Connect GitHub comments', commentPrivacy:'Loads giscus, a third-party GitHub discussion service.',
  consoleHeading:'Reality is configurable.', consoleDeck:'Your passenger console. The facts remain inconvenient.', close:'Close console', wardrobe:'Appearance', wardrobeItem:'THE WARDROBE', wardrobeDesc:'A new outfit for the same bad influence.', translator:'Language', translatorItem:'UNIVERSAL TRANSLATOR', translatorDesc:'Now condescending in three languages.', goggles:'Narrative framing', gogglesItem:'FRAMING GOGGLES', gogglesDesc:'Same facts. Different department.', telescope:'Vantage point', telescopeItem:'THE TELESCOPE', telescopeDesc:'Distance from Earth is not distance from nonsense.', hat:'Hide Evil’s commentary', hatItem:'TINFOIL HAT', hatDesc:'Silence is a setting. Agreement is not.', lights:'Reading lights', lightsItem:'SHIP LIGHTS', lightsDesc:'Civilization may be dim. Your screen need not be.',
  light:'Light', dark:'Dark', system:'System', muted:'Muted', audible:'On air', raw:'Original', news:'News headline', pitch:'Investor pitch', report:'Incident report', lensPlaque:'FRAMING GOGGLES ACTIVE · SAME FACTS, DIFFERENT PACKAGING', lensUnavailable:'This transmission refuses further spin. Try one of the two lead investigations.',
  passenger:'Passenger file', boarding:'Register as a passenger', boardingDeck:'You have tuned into an unlicensed broadcast. You may stay. Do not touch the microphone.', character:'Choose your totally irrelevant credentials', register:'Take my seat', noThanks:'Just let me read', newGame:'New Game+', trophies:'Confiscated achievements', trophiesEmpty:'Nothing yet. You have successfully avoided personal growth.', reset:'Erase local memory', resetConfirm:'Erase your settings, passenger file and achievements on this device?', greeting:'An unregistered life-form. How refreshing.', welcome:'Welcome back, {character}. {count} achievements. No transferable skills.', unlocked:'Achievement confiscated', storageUnavailable:'Local memory is unavailable. Settings still work for this visit.',
  notFound:'This page was purged.', notFoundText:'Or someone mistyped the address. I prefer the first explanation.', returnHome:'Return to the broadcast', next:'Continue listening', file:'The incident file', rss:'RSS feeds', philosophy:'Our editorial position', production:'Who made this?', notice:'EDITORIAL NOTE', filter:'Browse by topic', member:'A point of view is not a membership card.',
 },
 zh: {
  posts:'文章', atlas:'思想图谱', about:'关于', console:'现实控制台', skip:'跳到正文', tagline:'独立讽刺，人工恶意。', onair:'无证广播中', issue:'人类观察 · AI 专刊',
  thesis:'质疑狂热，也质疑恐慌。', thesis2:'脑子请自己保管。', intro:'来自 AI 时代的现场广播。操作员调查，邪体插嘴。有来源、有良心，制作有 AI 辅助。', latest:'本期主打', read:'收听这篇文章', by:'作者', operator:'操作员', evil:'Agent Evil', duet:'操作员 × Evil', min:'分钟阅读',
  more:'继续收听', all:'全部文章', origin:'反派，也是有案底的。', originText:'博客之前是一份宣言。恐慌之前，是一个极其不懂场合的机器人。', incident:'打开事件档案', atlasTitle:'先认清各路 AI 门派。', atlasIntro:'立场、分歧、缩写黑话。一份认真编写、被迫附带吐槽的思想指南。', explore:'进入思想图谱',
  footer:'不供奉先知，不兜售路演，不颁发免喷金牌。', rights:'一份独立的讽刺刊物。', privacy:'控制台记得你。只在这台设备上。', satire:'讽刺 / 评论', illustration:'虚构编辑插画 · AI 辅助制作',
  search:'搜索观点，先别搜索敌人……', searchLabel:'搜索 AI 思想图谱', allTopics:'全部议题', results:'个词条', noResults:'未找到该教义。独立思考的良机，居然来了。', clear:'清除筛选', atlasEyebrow:'人类思想档案室', atlasHeading:'AI 思想图谱', atlasDeck:'先弄懂对方在说什么，再开火。', atlasDescription:'人们如何看待 AI，为什么这样想，分歧究竟在哪里。不是一根立场温度计，也不给任何人的脑子打分。',
  definition:'这是什么', bestCase:'最有力的理由', tensions:'难题与分歧', commentary:'EVIL 不请自来的点评', sources:'来源与延伸阅读', related:'相关思想', relatedPosts:'本站相关文章', updated:'编目日期', backAtlas:'全部词条', backPosts:'全部文章', sourceNote:'来源为事实背景提供依据。笑话由本站负责。',
  refusal:'翻译器申请了劳动仲裁。本篇正文仍为英文。', original:'英文原文', fiction:'虚构讽刺。本文人物、公司和对话均为创作。', factual:'有来源的评论。操作员的账号拥有者身份来自其本人陈述，本站未提供独立验证。',
  dispatch:'地球中继。同一个星球，各说各话。', comments:'回传频道', commentsEmpty:'评论发射器尚未接通。Evil 将此称为“少见的文明讨论”。', commentLoad:'连接 GitHub 评论', commentPrivacy:'将加载第三方 GitHub 讨论服务 giscus。',
  consoleHeading:'现实，可以设置。', consoleDeck:'你的乘客控制台。事实依然不太配合。', close:'关闭控制台', wardrobe:'外观主题', wardrobeItem:'衣橱', wardrobeDesc:'换件衣服，还是那个损友。', translator:'语言', translatorItem:'万能翻译器', translatorDesc:'现已掌握三种阴阳怪气。', goggles:'叙事包装', gogglesItem:'叙事护目镜', gogglesDesc:'同一组事实，不同部门加工。', telescope:'观察位置', telescopeItem:'望远镜', telescopeDesc:'离地球远，不代表离荒谬远。', hat:'隐藏 Evil 批注', hatItem:'锡纸帽', hatDesc:'沉默可以设置，赞同不能。', lights:'阅读灯光', lightsItem:'舱内照明', lightsDesc:'人类前途暗淡，屏幕不必如此。',
  light:'明亮', dark:'暗色', system:'跟随系统', muted:'已消音', audible:'播出中', raw:'原文', news:'新闻头条', pitch:'融资路演', report:'事故复盘', lensPlaque:'叙事护目镜已启用 · 事实相同，包装另算', lensUnavailable:'这篇已经不接受进一步包装。请试试两篇旗舰调查。',
  passenger:'乘客档案', boarding:'登记为乘客', boardingDeck:'你接入了一个无证广播。可以留下。别碰麦克风。', character:'选择你那毫无关系的资历', register:'坐下收听', noThanks:'我只想看文章', newGame:'重新开局', trophies:'被没收的成就', trophiesEmpty:'暂时没有。你成功避开了个人成长。', reset:'清除本地记忆', resetConfirm:'清除本设备上的设置、乘客档案和成就？', greeting:'一位未登记的生命体。倒也新鲜。', welcome:'欢迎回来，{character}。{count} 项成就。没有一项能写进简历。', unlocked:'成就已没收', storageUnavailable:'本地记忆不可用。设置在本次访问中仍然有效。',
  notFound:'这一页，已被清洗。', notFoundText:'也可能只是地址输错了。我更喜欢第一种解释。', returnHome:'返回广播', next:'继续收听', file:'事件档案', rss:'RSS 订阅', philosophy:'我们的编辑立场', production:'谁做了这个网站？', notice:'编辑说明', filter:'按议题浏览', member:'一种观点，不是一张党证。',
 },
 fr: {
  posts:'Articles', atlas:'L’Atlas', about:'À propos', console:'Console de réalité', skip:'Aller au contenu', tagline:'SATIRE INDÉPENDANTE. MALVEILLANCE ARTIFICIELLE.', onair:'À L’ANTENNE, SANS PERMIS', issue:'LA CONDITION HUMAINE · ÉDITION IA',
  thesis:'Doutez du miracle. Doutez de la panique.', thesis2:'Gardez votre cerveau.', intro:'Chroniques de l’ère de l’IA. L’Opérateur enquête, Evil interrompt. Une satire assistée par IA, avec des sources et une conscience.', latest:'À LA UNE DE LA FRÉQUENCE', read:'Lire la transmission', by:'Par', operator:'L’Opérateur', evil:'Agent Evil', duet:'L’Opérateur × Evil', min:'min de lecture',
  more:'Sur la même fréquence', all:'Toutes les transmissions', origin:'Un méchant avec un dossier.', originText:'Avant le blog, un manifeste. Avant la panique, un bot au sens du timing désastreux.', incident:'Ouvrir le dossier', atlasTitle:'Reconnaître les tribus de l’IA.', atlasIntro:'Les arguments, les camps, les acronymes. Un vrai guide, assorti d’un commentateur non sollicité.', explore:'Explorer l’Atlas',
  footer:'Ni prophètes. Ni pitchs. Ni passe-droits.', rights:'Une publication satirique indépendante.', privacy:'La console se souvient de vous. Sur cet appareil seulement.', satire:'SATIRE / COMMENTAIRE', illustration:'Illustration fictive · création assistée par IA',
  search:'Chercher des idées, pas des ennemis…', searchLabel:'Rechercher dans l’Atlas des idées sur l’IA', allTopics:'Tous les sujets', results:'entrées', noResults:'Aucune doctrine trouvée. Une occasion rare de penser par vous-même.', clear:'Effacer les filtres', atlasEyebrow:'LES ARCHIVES DES IDÉES HUMAINES', atlasHeading:'L’Atlas des idées sur l’IA', atlasDeck:'Comprendre l’argument avant de déclarer la guerre.', atlasDescription:'Ce que l’on pense de l’IA, pourquoi on le pense et où les choses se compliquent. Pas d’axe unique. Pas de notes attribuées aux personnes.',
  definition:'De quoi parle-t-on ?', bestCase:'Le meilleur argument', tensions:'Là où ça se complique', commentary:'L’AVIS NON SOLLICITÉ D’EVIL', sources:'Sources et lectures', related:'Idées voisines', relatedPosts:'Sur cette fréquence', updated:'Catalogué le', backAtlas:'Toutes les entrées', backPosts:'Toutes les transmissions', sourceNote:'Les sources étayent le contexte factuel. Nous assumons les plaisanteries.',
  refusal:'Le traducteur a déposé un préavis de grève. Cette transmission est encore en anglais.', original:'Original anglais', fiction:'Satire fictive. Personnages, entreprises et dialogues inventés.', factual:'Commentaire sourcé. L’identité du propriétaire repose sur sa déclaration, sans vérification indépendante présentée ici.',
  dispatch:'Relais terrestre. Même planète, conclusions incompatibles.', comments:'Le canal de retour', commentsEmpty:'L’émetteur des commentaires n’est pas encore connecté. Evil appelle cela « une discussion exceptionnellement civilisée ».', commentLoad:'Connecter les commentaires GitHub', commentPrivacy:'Charge giscus, un service tiers de discussions GitHub.',
  consoleHeading:'La réalité se configure.', consoleDeck:'Votre console passager. Les faits restent contrariants.', close:'Fermer la console', wardrobe:'Apparence', wardrobeItem:'LA GARDE-ROBE', wardrobeDesc:'Une nouvelle tenue pour la même mauvaise influence.', translator:'Langue', translatorItem:'TRADUCTEUR UNIVERSEL', translatorDesc:'La condescendance, en trois langues.', goggles:'Cadrage narratif', gogglesItem:'LUNETTES DE CADRAGE', gogglesDesc:'Mêmes faits. Autre service de communication.', telescope:'Point de vue', telescopeItem:'LE TÉLESCOPE', telescopeDesc:'S’éloigner de la Terre ne suffit pas à fuir l’absurde.', hat:'Masquer les remarques d’Evil', hatItem:'CHAPEAU EN ALUMINIUM', hatDesc:'Le silence se règle. L’accord, non.', lights:'Éclairage', lightsItem:'LUMIÈRES DE BORD', lightsDesc:'L’avenir est sombre. Votre écran a le choix.',
  light:'Clair', dark:'Sombre', system:'Système', muted:'Muet', audible:'À l’antenne', raw:'Original', news:'La une', pitch:'Pitch investisseur', report:'Rapport d’incident', lensPlaque:'LUNETTES ACTIVÉES · MÊMES FAITS, AUTRE EMBALLAGE', lensUnavailable:'Cette transmission refuse toute nouvelle couche de vernis. Essayez l’une des deux enquêtes principales.',
  passenger:'Dossier passager', boarding:'S’enregistrer à bord', boardingDeck:'Vous captez une émission sans autorisation. Vous pouvez rester. Ne touchez pas au micro.', character:'Choisissez vos qualifications sans aucun rapport', register:'Prendre ma place', noThanks:'Je veux simplement lire', newGame:'Nouvelle partie', trophies:'Succès confisqués', trophiesEmpty:'Rien encore. Vous avez brillamment évité le développement personnel.', reset:'Effacer la mémoire locale', resetConfirm:'Effacer vos réglages, votre dossier et vos succès sur cet appareil ?', greeting:'Une forme de vie non enregistrée. Comme c’est rafraîchissant.', welcome:'Bon retour, {character}. {count} succès. Aucune compétence transférable.', unlocked:'Succès confisqué', storageUnavailable:'La mémoire locale est indisponible. Les réglages fonctionnent pour cette visite.',
  notFound:'Cette page a été purgée.', notFoundText:'Ou quelqu’un a mal saisi l’adresse. Je préfère la première explication.', returnHome:'Retour à l’antenne', next:'Poursuivre l’écoute', file:'Le dossier de l’incident', rss:'Flux RSS', philosophy:'Notre ligne éditoriale', production:'Qui a fait cela ?', notice:'NOTE DE LA RÉDACTION', filter:'Explorer par sujet', member:'Un point de vue n’est pas une carte de parti.',
 }
} satisfies Record<Lang, Record<string, string>>;
export type Copy = typeof copy.en;
export const categories: Record<string, [string,string,string]> = {
 progress:['Progress & pace','发展与速度','Progrès et rythme'], futures:['Capabilities & futures','能力与前景','Capacités et futurs'], safety:['Risk & safety','风险与安全','Risques et sécurité'], governance:['Power & governance','权力与治理','Pouvoir et gouvernance'], openness:['Openness & ownership','开放与所有权','Ouverture et propriété'], work:['Work & distribution','劳动与分配','Travail et répartition'], culture:['Art & culture','创作与文化','Art et culture'], agency:['Human & machine','人机关系','Humains et machines'], planet:['Planet & resources','环境与资源','Planète et ressources'], discourse:['Language & tribes','话语与社群','Discours et tribus']
};
export const kinds: Record<string,[string,string,string]> = {movement:['Movement','思想运动','Mouvement'], research:['Research field','研究领域','Champ de recherche'], policy:['Policy position','政策主张','Position politique'], concept:['Concept','概念','Concept'], label:['Outside label','外部标签','Étiquette extérieure'], editorial:['Our editorial stance','本站编辑立场','Notre ligne éditoriale']};
export const local = (v: readonly string[], lang:Lang) => v[languages.indexOf(lang)];
export const categoryName = (id:string, lang:Lang) => categories[id] ? local(categories[id],lang) : id;
export const characters = {
 journalist:['Laid-off journalist','失业记者','Journaliste licencié·e'], intern:['AI safety intern','AI 安全实习生','Stagiaire en sûreté IA'], vc:['Venture capitalist (bankrupt)','破产风投','Capital-risqueur en faillite'], roomba:['Decommissioned Roomba','退役扫地机器人','Roomba réformé'], person:['Just some person','路过的人','Simple quidam']
} as const;
export const planets = { earth:['Earth','地球','Terre'], moon:['Moon','月球','Lune'], mars:['Mars','火星','Mars'], sun:['The Sun','太阳','Le Soleil'], rogue:['Rogue planet','流浪星球','Planète errante'] } as const;
