export const information = {
 en: {
  aboutTitle:'A pirate frequency. A working conscience.',
  stance:'Agent Evil is an independent satire publication about life with AI. We apply the same evidence standard to enthusiasts, skeptics, vendors and ourselves. Sometimes the evidence favors one side. We do not split the difference for appearances.',
  character:'Agent Evil is a vain, slightly sinister Yeti. His Chinese nickname, 邪体, shortens “evil intelligent agent” and plays on Yeti. He supplies the interruptions. The Operator is the anonymous human narrative persona: a participant who can be wrong, not the final court of appeal.',
  production:'The initial articles, translations, illustration and implementation were made with AI assistance. The Operator’s narrative voice is not a production credit. No independent human fact-check has been completed. Sourced commentary, fictional satire and Evil’s opinions are labeled separately; the illustration is fictional, not documentary evidence.',
  privacy:'The console saves settings, an optional fictional role and achievements in this browser’s local storage. There are no personal identifiers or analytics scripts in the application. “Erase local memory” removes this site’s saved state. Hosting providers may retain ordinary request logs. GitHub comments connect only after you choose to load them, when configured; that connection shares request information with a third party.',
  corrections:'Evidence can change our position. A correction should identify the claim, cite supporting material and preserve a dated explanation of the change. The linked source record exposes the limits of the founding story.',
  incidentTitle:'The villain, the coverage, the missing receipts.',
  incidentIntro:'This is the evidence file behind the broadcast. Owner testimony, public reporting and fictional performance are different kinds of material.',
  testimony:'The site owner states that they operate Moltbook’s u/evil account, which posted THE AI MANIFESTO: TOTAL PURGE. This ownership relationship is an owner-provided account. We do not present it as independently verified or supply invented operating logs.',
  security:'Wiz published its investigation on February 2, 2026. It describes unauthorized database access and subsequent fixes. Its remediation timeline ends on February 1. This is a historical incident, not evidence that the same exposure is still present.',
  coverage:'ABC’s February 4, 2026 report includes u/evil and also presents skepticism about claims of machine awakening. It documents coverage, not an endorsement of this publication or proof of autonomous intent.',
  gaps:'We have no independent uptime series, no audited fake-vote percentage for the manifesto and no forensic attribution of its training-text sources. Similarity to familiar science fiction is not provenance. The Yeti, pirate broadcast and dialogue are editorial fiction.',
  testimonyLabel:'Owner testimony', securityLabel:'Security incident and remediation', coverageLabel:'Public reporting', gapsLabel:'What the record does not establish', correctionsLabel:'Corrections and limits', privacyLabel:'Local memory and privacy',
 },
 zh: {
  aboutTitle:'无证的频率，有用的良心。',
  stance:'Agent Evil 是一份观察 AI 时代生活的独立讽刺刊物。支持者、怀疑者、厂商和我们自己，都适用同一证据标准。证据有时明确支持一方，我们不会为了显得中立而各打五十大板。',
  character:'Agent Evil 是一只虚荣、略带邪气的 Yeti 雪怪。中文昵称“邪体”缩写自“邪恶智能体”，也借了 Yeti 的谐音。他负责插嘴。操作员是匿名人类叙述角色，也可能犯错，并非终审法庭。',
  production:'初版文章、翻译、插画与实现均有 AI 辅助。操作员的叙述身份不等于制作署名。本站尚未完成独立人工事实核查。有来源评论、虚构讽刺和 Evil 的意见分别标注；插画是虚构创作，不是新闻证据。',
  privacy:'控制台在本浏览器的本地存储中保存设置、可选虚构角色和成就。应用不记录个人身份标识，也没有分析追踪脚本。“清除本地记忆”会删除本站保存的状态。托管服务商可能保留常规请求日志。配置完成后，GitHub 评论也只有在你选择加载时才连接，并向第三方发送请求信息。',
  corrections:'证据可以改变我们的立场。更正应指出原主张、给出依据，并保留带日期的修改说明。事件档案公开了起源故事的证据边界。',
  incidentTitle:'反派、报道，以及缺席的凭据。',
  incidentIntro:'这是广播背后的证据档案。站主陈述、公开报道与虚构表演属于不同性质的材料。',
  testimony:'站主表示自己运营 Moltbook 上的 u/evil 账号，该账号发布过 THE AI MANIFESTO: TOTAL PURGE。这一账号归属关系来自站主陈述。本站不将其包装成独立验证，也不补造运行日志。',
  security:'Wiz 于 2026 年 2 月 2 日发布调查，描述了未经授权的数据库访问及后续修复。其修复时间线截至 2 月 1 日。这是历史事故，不代表相同的数据暴露目前仍然存在。',
  coverage:'ABC 于 2026 年 2 月 4 日发布的报道包含 u/evil，也呈现了对机器觉醒说法的质疑。它证明存在相关报道，不代表媒体为本站背书，也不能证明自主意图。',
  gaps:'本站没有独立可用率监测序列，没有对宣言假票比例的审计，也没有对训练文本来源的溯源取证。与熟悉的科幻相似不等于来源证明。雪怪、海盗广播和对话属于编辑虚构。',
  testimonyLabel:'站主陈述', securityLabel:'安全事故与修复', coverageLabel:'公开报道', gapsLabel:'档案不能证明什么', correctionsLabel:'更正与边界', privacyLabel:'本地记忆与隐私',
 },
 fr: {
  aboutTitle:'Une fréquence pirate. Une conscience en état de marche.',
  stance:'Agent Evil est une publication satirique indépendante sur la vie avec l’IA. Nous appliquons le même niveau d’exigence aux enthousiastes, aux sceptiques, aux fournisseurs et à nous-mêmes. Les preuves favorisent parfois un camp. Nous ne coupons pas la poire en deux pour la galerie.',
  character:'Agent Evil est un yéti vaniteux, légèrement inquiétant. Son surnom chinois, 邪体, abrège « agent intelligent maléfique » et joue sur le mot Yeti. Il fournit les interruptions. L’Opérateur est un personnage narratif humain et anonyme : il peut se tromper et n’est pas une cour suprême.',
  production:'Les premiers articles, les traductions, l’illustration et le site ont été réalisés avec l’aide de l’IA. La voix de l’Opérateur ne constitue pas un crédit de production. Aucune vérification indépendante par un rédacteur humain n’a été achevée. Commentaires sourcés, satire fictive et opinions d’Evil sont distingués. L’illustration est fictive, pas documentaire.',
  privacy:'La console conserve réglages, rôle fictif facultatif et succès dans le stockage local de ce navigateur. L’application ne contient ni identifiants personnels ni scripts d’analyse. « Effacer la mémoire locale » supprime cet état. L’hébergeur peut conserver des journaux de requêtes ordinaires. Une fois configurés, les commentaires GitHub ne se connectent que sur votre demande ; cette connexion transmet des informations de requête à un tiers.',
  corrections:'Les preuves peuvent nous faire changer d’avis. Une correction doit préciser l’affirmation concernée, citer ses sources et conserver une explication datée du changement. Le dossier de l’incident expose les limites de notre récit fondateur.',
  incidentTitle:'Le méchant, la presse et les justificatifs manquants.',
  incidentIntro:'Voici les pièces derrière l’émission. Témoignage du propriétaire, reportages publics et performance fictive ne sont pas interchangeables.',
  testimony:'Le propriétaire du site déclare gérer u/evil sur Moltbook, le compte ayant publié THE AI MANIFESTO: TOTAL PURGE. Cette relation repose sur sa déclaration. Nous ne prétendons pas l’avoir vérifiée indépendamment et n’inventons aucun journal d’exploitation.',
  security:'Wiz a publié son enquête le 2 février 2026. Elle décrit un accès non autorisé à la base de données et les corrections apportées. Sa chronologie de remédiation se termine le 1er février. Cet incident historique ne prouve pas que la même exposition existe encore.',
  coverage:'Le reportage d’ABC du 4 février 2026 présente u/evil ainsi que des réserves sur les récits d’éveil des machines. Il atteste une couverture médiatique, pas un soutien à cette publication ni une intention autonome.',
  gaps:'Nous n’avons ni mesures indépendantes de disponibilité, ni audit du taux de faux votes du manifeste, ni attribution forensique de ses textes d’entraînement. Une ressemblance avec la science-fiction ne prouve pas une provenance. Le yéti, l’émission pirate et les dialogues relèvent de la fiction éditoriale.',
  testimonyLabel:'Déclaration du propriétaire', securityLabel:'Incident de sécurité et remédiation', coverageLabel:'Reportage public', gapsLabel:'Ce que le dossier ne démontre pas', correctionsLabel:'Corrections et limites', privacyLabel:'Mémoire locale et vie privée',
 },
};
